

# # costmap_common.yaml


obstacle_layer:
  enabled: true
  observation_sources: semantic_obstacles
  semantic_obstacles:
    data_type: OccupancyGrid
    topic: /semantic_costmap
    frame_id: base_link  # Critical! Camera data relative to robot

    marking: true
    clearing: false
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0
    expected_update_rate: 1.0
    observation_persistence: 1.0  # Keep observations for 1 second

inflation_layer:
  enabled: true
  inflation_radius: 0.5
  cost_scaling_factor: 5.0


# # Common Parameters
# obstacle_range: 2.5
# raytrace_range: 3.0
# transform_tolerance: 0.2
# update_frequency: 5.0
# publish_frequency: 2.0
# rolling_window: true
# track_unknown_space: true

# robot_radius: 0.25  # Set robot radius or define footprint in local/global costmaps

# inflation_layer:
#   enabled: true
#   inflation_radius: 0.45   # Reduced from 0.3 to be less conservative
#   cost_scaling_factor: 5.0 # Slightly lower cost scaling for better path clearance
#   inflate_unknown: false
#   inflate_around_unknown: false

# static_layer:
#   enabled: true
#   map_topic: "/semantic_costmap"
#   subscribe_to_updates: true
#   track_unknown_space: false
#   combination_method: 1
#   trinary_costmap: false
#   unknown_cost_value: 255
#   lethal_cost_threshold: 254  # Increased to allow more tolerance


#---------------------------------------------------------------------------------------
#   # Robot Footprint
# footprint: [[-0.25, -0.25],
#             [-0.25, 0.25],
#             [0.25, 0.25],
#             [0.25, -0.25]]


# # costmap_common.yaml


# # Common Parameters
# obstacle_range: 2.5
# raytrace_range: 3.0
# transform_tolerance: 0.2
# update_frequency: 5.0
# publish_frequency: 2.0
# rolling_window: true
# track_unknown_space: true


# # robot_radius: 0.25

# # Inflation Layer
# inflation_layer:
#   enabled: true
#   inflation_radius: 0.3
#   cost_scaling_factor: 5.0
#   inflate_unknown: false
#   inflate_around_unknown: false

# # Static Layer (Semantic Costmap)
# static_layer:
#   enabled: true
#   map_topic: "/semantic_costmap"

#   subscribe_to_updates: true
#   track_unknown_space: true
#   combination_method: 1
#   trinary_costmap: false   # true: Forces clear free/occupied distinction # false: Allows gradient costs
#   # unknown_cost_value: 255
#   unknown_cost_value: 0  # Treat unknown as free space (was -1)

#   lethal_cost_threshold: 100

  

# # Global Planner Parameters
# GlobalPlanner:
#   allow_unknown: true  # Critical for navigating to unknown areas
#   default_tolerance: 0.5
#   use_dijkstra: false  # A* is generally better for exploration
#   use_grid_path: false  # Use gradient path for smoother navigation
#   old_navfn_behavior: false
#   # # Robot Footprint
# # footprint: [[-0.25, -0.25],
# #             [-0.25, 0.25],
# #             [0.25, 0.25],
# #             [0.25, -0.25]]