analyzers:
  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      gps:
        type: diagnostic_aggregator/GenericAnalyzer
        path: GPS
        contains: 'gps_driver'