# DWAPlannerROS:
#   holonomic_robot: false
#   max_vel_trans: 0.2

#   # Velocity limits
#   max_vel_x: 0.4
#   min_vel_x: 0.02
#   max_vel_theta: 0.4
#   min_vel_theta: 0.1
#   max_trans_vel: 0.2
#   min_trans_vel: 0.02

#   # Acceleration limits
#   acc_lim_x: 0.1
#   acc_lim_theta: 0.1

#   # Trajectory Scoring
#   path_distance_bias: 35.0
#   goal_distance_bias: 20.0
#   occdist_scale: 0.05
#   forward_point_distance: 0.5

#   # Goal Tolerances
#   xy_goal_tolerance: 0.1
#   yaw_goal_tolerance: 0.15

#   # Simulation Parameters
#   sim_time: 1.0
#   sim_granularity: 0.025
#   vx_samples: 20
#   vtheta_samples: 40

#   # Stop any y sampling
#   vy_samples: 0







# DWAPlannerROS:
#   # Velocity Limits
#   max_vel_x: 0.5
#   min_vel_x: 0.05
#   max_vel_theta: 0.8
#   min_vel_theta: -0.8

#   # Acceleration Limits
#   acc_lim_x: 0.3                  # Reduced
#   acc_lim_theta: 1.0              # Reduced
#   decel_lim_x: 1.0               
#   decel_lim_theta: 1.5           

#   # Trajectory Generation
#   sim_time: 2.0                   # Increased
#   vx_samples: 12                  # Reduced
#   vtheta_samples: 24              # Reduced
#   sim_granularity: 0.025
#   angular_sim_granularity: 0.025

#   # Goal Tolerance
#   xy_goal_tolerance: 0.15
#   yaw_goal_tolerance: 0.3

#   # Scoring Weights
#   path_distance_bias: 64.0         # Reduced
#   goal_distance_bias: 16.0         # Increased
#   occdist_scale: 0.1
#   forward_point_distance: 0.325
#   scaling_speed: 0.1               # Reduced
#   max_scaling_factor: 0.15         # Reduced

#   # System Configuration
#   holonomic_robot: false


# DWAPlannerROS:
DWAPlannerROS:
  holonomic_robot: false


  # Basic Parameters
  # max_vel_trans: 0.2
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: 0.4
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  acc_lim_y: 0.0

  # Goal Tolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1

  # Trajectory Planning
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  vx_samples: 3
  vy_samples: 0
  vth_samples: 20

  # Obstacle Avoidance
  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  occdist_scale: 0.01
  forward_point_distance: 0.325
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Recovery
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
  prune_plan: false