

# VO (/odometry/stereo): for full 3D pose and velocity

# IMU (/imu/data): for orientation and angular velocity

# Mag (/mag): for yaw drift correction

frequency: 30.0
transform_tolerance: 0.1

sensor_timeout: 0.2
# map_frame: vo
# map_frame: odom
odom_frame: odom # Different from map_frame
base_link_frame: base_link
world_frame: odom
print_diagnostics: true
debug: true
publish_tf: true  # Must be enabled


two_d_mode: true                # Constrain to 2D plane
# transform_time_offset: 0.0      # No artificial delay
# transform_timeout: 0.0          # Disable transform timeout
predict_to_current_time: true   # Critical for high-frequency IMU


# Stereo Odometry (primary)
odom0: /odometry/stereo
odom0_config: [true, true, false,    # Full XYZ
               true, true, false,     # Full velocity
               false, false, false,
               false, false, true,
               false, false, false]
odom0_differential: true  # Should be true for VO
odom0_relative: true      # Should be true for VO
odom0_queue_size: 5

# IMU (high-frequency)
imu0: /imu/data
imu0_config: [false, false, false,
              true,  true,  false,  # Roll/pitch only
              false, false, false,
              true,  true,  true,   # Angular velocity
              false, false, false]  # No linear accel 
imu0_queue_size: 10

# Magnetometer (heading correction)
mag0: /mag
mag0_config: [false, false, false,
              false, false, false,  # Fuse yaw only
              false, false, false,
              false, false, false,
              false, false, false]
mag0_differential: false

mag0_queue_size: 10


# frequency: 20.0
# sensor_timeout: 0.05
# map_frame: vo
# odom_frame: odom
# base_link_frame: base_link
# world_frame: odom
# # publish_tf: true

# predict_to_current_time: true
# print_diagnostics: true

# # Stereo Odometry
# odom0: /odometry/stereo
# odom0_config: [true, true, false,  # Fuse XY position
#                true, true, false,   # Fuse XY velocity
#                false, false, false,
#                false, false, false,
#                false, false, false]
# odom0_differential: true
# odom0_queue_size: 5

# # IMU
# imu0: /imu/data
# imu0_config: [false, false, false,
#               true,  true,  true,    # Orientation
#               false, false, false,
#               true,  true,  true,    # Angular velocity
#               true,  true,  true]    # Linear acceleration
# imu0_queue_size: 20