
  


# # # global_costmap.yaml


# global_frame: odom
# robot_base_frame: base_link

# update_frequency: 2.0        # Global map doesn't need to update too frequently
# publish_frequency: 2.0
# width: 50.0
# height: 50.0
# resolution: 0.05

# # origin_x: -25.0
# # origin_y: -2.0
# rolling_window: true  # Must match local costmap behavior


# plugins:
#   - {name: static_layer, type: "costmap_2d::StaticLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

# static_layer:
#   map_topic: /semantic_costmap
#   subscribe_to_updates: true
#   track_unknown_space: true
#   combination_method: 1
#   enabled: true




  


# # # global_costmap.yaml


global_frame: odom
robot_base_frame: base_link

update_frequency: 10.0        # Global map doesn't need to update too frequently
publish_frequency: 2.0
width: 20.0
height: 20.0
resolution: 0.05

# origin_x: -25.0
# origin_y: -2.0
rolling_window: true  # Must match local costmap behavior



plugins:
  - {name: semantic_layer, type: "costmap_2d::StaticLayer"}  # Changed from static_layer
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

semantic_layer:
  map_topic: /semantic_costmap
  subscribe_to_updates: true
  track_unknown_space: true
  combination_method: 1  # Overwrite, not accumulate




# global_frame: map  # Changed from 'map' to 'odom'
# robot_base_frame: base_link

# update_frequency: 2.0
# publish_frequency: 2.0
# width: 20.0
# height: 20.0
# resolution: 0.05

# rolling_window: true

# plugins:
#   - {name: semantic_layer, type: "costmap_2d::StaticLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

# semantic_layer:
#   map_topic: /semantic_costmap
#   subscribe_to_updates: true
#   track_unknown_space: true
#   combination_method: 1
#   enabled: true