# GlobalPlanner:
#   use_dijkstra: false
#   use_astar: true
#   use_quadratic: true
#   use_grid_path: false
#   lethal_cost: 100
#   neutral_cost: 10  # Lowered for sidewalk preference
#   cost_factor: 3.0
#   allow_unknown: true  # CRITICAL for dynamic semantic maps
#   planner_window_x: 50.0
#   planner_window_y: 50.0
#   publish_potential: true
#   publish_scale: 100
#   orientation_mode: 0


GlobalPlanner:
  use_dijkstra: false       # Using A* as requested
  use_astar: true           # Enable A* algorithm
  use_quadratic: true       # Smoother interpolation
  use_grid_path: false      # Use gradient path instead of grid path
  lethal_cost: 100          # Standard occupancy threshold
  neutral_cost: 50          # Balanced cost for unexplored areas
  cost_factor: 3.0          # Aggressive path smoothing
  allow_unknown: true       # Essential for dynamic semantic maps
  planner_window_x: 20.0    # More reasonable window size
  planner_window_y: 20.0
  publish_potential: true   # For visualization
  publish_scale: 100
  orientation_mode: 0       # No orientation constraints
  old_navfn_behavior: false # Modern behavior
  outline_map: false
