TebLocalPlannerROS:

  # Robot Configuration
  max_vel_x: 0.4               # Maximum linear velocity (m/s)
  max_vel_x_backwards: 0.2     # Maximum reverse velocity (m/s)
  max_vel_theta: 0.5           # Maximum angular velocity (rad/s)
  acc_lim_x: 0.5               # Linear acceleration limit (m/s²)
  acc_lim_theta: 0.7           # Angular acceleration limit (rad/s²)
  
  # Goal Tolerance
  xy_goal_tolerance: 0.1       # Position tolerance (m)
  yaw_goal_tolerance: 0.1      # Orientation tolerance (rad)
  free_goal_vel: false         # Allow non-zero velocity at goal
  
  # Trajectory Optimization
  dt_ref: 0.3                  # Time step between trajectory points
  dt_hysteresis: 0.1           # Allow time step variation
  min_samples: 3               # Minimum trajectory points
  max_samples: 500             # Maximum trajectory points
  
  # Obstacle Avoidance
  min_obstacle_dist: 0.25      # Minimum distance from obstacles (m)
  inflation_dist: 0.3          # Inflation radius for obstacles
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  
  # Optimization Weights (tune these carefully)
  weight_kinematics_nh: 1000   # Non-holonomic constraint
  weight_kinematics_forward_drive: 1  # Prefer forward motion
  weight_optimaltime: 1        # Time-optimal trajectory
  weight_obstacle: 50          # Obstacle avoidance
  
  # Differential Drive Parameters
  footprint_model:
    type: "point"              # "point", "circular", or "two_circles"
    radius: 0.3                # Used if type is "circular"
  
  # Visualization
  enable_homotopy_class_planning: true  # Consider alternative paths
  visualization_teb_markers: true      # RViz visualization
  visualization_obstacles: true